version: '3.1'

services:
  api:
    build: app
    command: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always
    networks:
      - backend

  mongo:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
